apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: edgerouter
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 172.16.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: edgerouter
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
