apiVersion: batch/v1
kind: CronJob
metadata:
  name: wordpress-cron
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: wordpress-persistent-storage
            persistentVolumeClaim:
              claimName: wp-pv-claim
          containers:
          - name: wp-cron
            image: arm64v8/wordpress:5.8.1-apache
            command: ["/usr/local/bin/php"]
            args:
            - /var/www/html/wp-cron.php
            volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            env:
              - name: WORDPRESS_DB_HOST
                value: mysql-0.mysql
              - name: WORDPRESS_DB_USER
                value: wordpress
              - name: WORDPRESS_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-pass
                    key: password
          restartPolicy: OnFailure

